# version: '3'
services:
  test-webserver:
    container_name: test-webserver
    image: arm64v8/httpd:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./webtest:/usr/local/apache2/htdocs:ro