# version: '3'
services:
  test-webserver:
    container_name: test-webserver
    image: arm64v8/httpd:latest
    restart: unless-stopped
    volumes:
      - ./webtest:/usr/local/apache2/htdocs:ro
    networks:
      - proxy-network

  nginx-reverse-proxy:
    container_name: nginx-reverse-proxy
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt/:ro
      - ./certbot/www:/var/www/certbot/:ro
    networks:
      - proxy-network

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt/:rw
      - ./certbot/www:/var/www/certbot/:rw
    command: certonly --webroot -w /var/www/certbot --keep-until-expiring --email robin.schaefer@students.hs-mainz.de -d collectiqo.com -d www.collectiqo.com --agree-tos --no-eff-email
    networks:
      - proxy-network

networks:
    proxy-network:
        driver: bridge