# version: '3'
services:
  web-test:
    container_name: web-test
    image: dragas/thttpd:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - "./thttpd:/home/static:ro"