# version: '3'
services:
  web:
    container_name: collectiqo-web-1
    image: clq-app
    env_file: ./.env.docker
    ports:
      - "${PORT}:${PORT}"
    volumes:
      #- ~/.certificates/collectiqo/:/root/.certificates/collectiqo:ro # mount local keys into container for dev purposes
      - /home/collectiqo/local_cert/collectiqo_rs:/root/.certificates/collectiqo:ro # mount local keys into container for dev purposes
    networks:
      - proxy-network
      #- app-network
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  mysql:
    container_name: collectiqo-mysql-1
    image: lorackdev/clq-mysql-multiarch
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
    ports:
      - "${MYSQL_DATABASE_PORT}:${MYSQL_DATABASE_PORT}"
    networks:
      - proxy-network
      #- app-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQL_DATABASE_PASSWORD}"]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 9


  mongodb:
    container_name: collectiqo-mongodb-1
    image: mongo:latest
    restart: always
    ports:
      - "${MONGO_DATABASE_PORT}:${MONGO_DATABASE_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DATABASE_PASSWORD}
    networks:
      - proxy-network
      #- app-network
    healthcheck:
      #test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      #test: echo 'db.runCommand("ping").ok' | mongosh mongodb:27017/test --quiet
      test: echo 'db.runCommand("ping").ok' | mongosh collectiqo-mongodb-1:27017/test --quiet
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 9


  test-webserver:
    container_name: test-webserver
    image: arm64v8/httpd:latest
    restart: unless-stopped
    volumes:
      - ./webtest:/usr/local/apache2/htdocs:ro
    networks:
      - proxy-network

  nginx-reverse-proxy:
    container_name: nginx-reverse-proxy
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt/:ro
      - ./certbot/www:/var/www/certbot/:ro
    networks:
      - proxy-network
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://localhost/ || exit 1"]
      start_period: 15s
      interval: 15s
      timeout: 15s
      retries: 3

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt/:rw
      - ./certbot/www:/var/www/certbot/:rw
    networks:
      - proxy-network
    depends_on:
      nginx-reverse-proxy:
        condition: service_healthy

networks:
  app-network:
    driver: bridge
  proxy-network:
    driver: bridge